resources:
- ../base
- env-ops-configmap.yaml
- r6/configmap.yaml

patches:
- path: traffic-routing.yaml
  target:
    kind: Service
- path: r6/revision-patch.yaml
  target:
    kind: Service
- path: r6/routing-patch.yaml
  target:
    kind: Service