resources:
- ../base
- env-ops-configmap.yaml
- rnew3/configmap.yaml

patches:
- path: traffic-routing.yaml
  target:
    kind: Service
- path: rnew3/revision-patch.yaml
  target:
    kind: Service
- path: rnew3/routing-patch.yaml
  target:
    kind: Service