resources:
- ../base
- env-ops-configmap.yaml
- r4/configmap.yaml

patches:
- path: traffic-routing.yaml
  target:
    kind: Service
- path: r4/revision-patch.yaml
  target:
    kind: Service
- path: r4/routing-patch.yaml
  target:
    kind: Service