resources:
- ../base
- env-ops-configmap.yaml
- r7/configmap.yaml

patches:
- path: traffic-routing.yaml
  target:
    kind: Service
- path: r7/revision-patch.yaml
  target:
    kind: Service
- path: r7/routing-patch.yaml
  target:
    kind: Service